/**
 * google-cloud-speech-languages
 * admin.get-native.com
 *
 * Created by henryehly on 2017/05/30.
 */

/* Taken from https://cloud.google.com/speech/docs/languages
 * Formatted at http://convertjson.com/html-table-to-json.htm */
export const GoogleCloudSpeechLanguages = [
    ['Afrikaans (Suid-Afrika)', 'af-ZA', 'Afrikaans (South Africa)'],
    ['Bahasa Indonesia (Indonesia)', 'id-ID', 'Indonesian (Indonesia)'],
    ['Bahasa Melayu (Malaysia)', 'ms-MY', 'Malay (Malaysia)'],
    ['Català (Espanya)', 'ca-ES', 'Catalan (Spain)'],
    ['Čeština (Česká republika)', 'cs-CZ', 'Czech (Czech Republic)'],
    ['Dansk (Danmark)', 'da-DK', 'Danish (Denmark)'],
    ['Deutsch (Deutschland)', 'de-DE', 'German (Germany)'],
    ['English (Australia)', 'en-AU', 'English (Australia)'],
    ['English (Canada)', 'en-CA', 'English (Canada)'],
    ['English (Great Britain)', 'en-GB', 'English (United Kingdom)'],
    ['English (India)', 'en-IN', 'English (India)'],
    ['English (Ireland)', 'en-IE', 'English (Ireland)'],
    ['English (New Zealand)', 'en-NZ', 'English (New Zealand)'],
    ['English (Philippines)', 'en-PH', 'English (Philippines)'],
    ['English (South Africa)', 'en-ZA', 'English (South Africa)'],
    ['English (United States)', 'en-US', 'English (United States)'],
    ['Español (Argentina)', 'es-AR', 'Spanish (Argentina)'],
    ['Español (Bolivia)', 'es-BO', 'Spanish (Bolivia)'],
    ['Español (Chile)', 'es-CL', 'Spanish (Chile)'],
    ['Español (Colombia)', 'es-CO', 'Spanish (Colombia)'],
    ['Español (Costa Rica)', 'es-CR', 'Spanish (Costa Rica)'],
    ['Español (Ecuador)', 'es-EC', 'Spanish (Ecuador)'],
    ['Español (El Salvador)', 'es-SV', 'Spanish (El Salvador)'],
    ['Español (España)', 'es-ES', 'Spanish (Spain)'],
    ['Español (Estados Unidos)', 'es-US', 'Spanish (United States)'],
    ['Español (Guatemala)', 'es-GT', 'Spanish (Guatemala)'],
    ['Español (Honduras)', 'es-HN', 'Spanish (Honduras)'],
    ['Español (México)', 'es-MX', 'Spanish (Mexico)'],
    ['Español (Nicaragua)', 'es-NI', 'Spanish (Nicaragua)'],
    ['Español (Panamá)', 'es-PA', 'Spanish (Panama)'],
    ['Español (Paraguay)', 'es-PY', 'Spanish (Paraguay)'],
    ['Español (Perú)', 'es-PE', 'Spanish (Peru)'],
    ['Español (Puerto Rico)', 'es-PR', 'Spanish (Puerto Rico)'],
    ['Español (República Dominicana)', 'es-DO', 'Spanish (Dominican Republic)'],
    ['Español (Uruguay)', 'es-UY', 'Spanish (Uruguay)'],
    ['Español (Venezuela)', 'es-VE', 'Spanish (Venezuela)'],
    ['Euskara (Espainia)', 'eu-ES', 'Basque (Spain)'],
    ['Filipino (Pilipinas)', 'fil-PH', 'Filipino (Philippines)'],
    ['Français (Canada)', 'fr-CA', 'French (Canada)'],
    ['Français (France)', 'fr-FR', 'French (France)'],
    ['Galego (España)', 'gl-ES', 'Galician (Spain)'],
    ['Hrvatski (Hrvatska)', 'hr-HR', 'Croatian (Croatia)'],
    ['IsiZulu (Ningizimu Afrika)', 'zu-ZA', 'Zulu (South Africa)'],
    ['Íslenska (Ísland)', 'is-IS', 'Icelandic (Iceland)'],
    ['Italiano (Italia)', 'it-IT', 'Italian (Italy)'],
    ['Lietuvių (Lietuva)', 'lt-LT', 'Lithuanian (Lithuania)'],
    ['Magyar (Magyarország)', 'hu-HU', 'Hungarian (Hungary)'],
    ['Nederlands (Nederland)', 'nl-NL', 'Dutch (Netherlands)'],
    ['Norsk bokmål (Norge)', 'nb-NO', 'Norwegian Bokmål (Norway)'],
    ['Polski (Polska)', 'pl-PL', 'Polish (Poland)'],
    ['Português (Brasil)', 'pt-BR', 'Portuguese (Brazil)'],
    ['Português (Portugal)', 'pt-PT', 'Portuguese (Portugal)'],
    ['Română (România)', 'ro-RO', 'Romanian (Romania)'],
    ['Slovenčina (Slovensko)', 'sk-SK', 'Slovak (Slovakia)'],
    ['Slovenščina (Slovenija)', 'sl-SI', 'Slovenian (Slovenia)'],
    ['Suomi (Suomi)', 'fi-FI', 'Finnish (Finland)'],
    ['Svenska (Sverige)', 'sv-SE', 'Swedish (Sweden)'],
    ['Tiếng Việt (Việt Nam)', 'vi-VN', 'Vietnamese (Vietnam)'],
    ['Türkçe (Türkiye)', 'tr-TR', 'Turkish (Turkey)'],
    ['Ελληνικά (Ελλάδα)', 'el-GR', 'Greek (Greece)'],
    ['Български (България)', 'bg-BG', 'Bulgarian (Bulgaria)'],
    ['Русский (Россия)', 'ru-RU', 'Russian (Russia)'],
    ['Српски (Србија)', 'sr-RS', 'Serbian (Serbia)'],
    ['Українська (Україна)', 'uk-UA', 'Ukrainian (Ukraine)'],
    ['עברית (ישראל)', 'he-IL', 'Hebrew (Israel)'],
    ['العربية (إسرائيل)', 'ar-IL', 'Arabic (Israel)'],
    ['العربية (الأردن)', 'ar-JO', 'Arabic (Jordan)'],
    ['العربية (الإمارات)', 'ar-AE', 'Arabic (United Arab Emirates)'],
    ['العربية (البحرين)', 'ar-BH', 'Arabic (Bahrain)'],
    ['العربية (الجزائر)', 'ar-DZ', 'Arabic (Algeria)'],
    ['العربية (السعودية)', 'ar-SA', 'Arabic (Saudi Arabia)'],
    ['العربية (العراق)', 'ar-IQ', 'Arabic (Iraq)'],
    ['العربية (الكويت)', 'ar-KW', 'Arabic (Kuwait)'],
    ['العربية (المغرب)', 'ar-MA', 'Arabic (Morocco)'],
    ['العربية (تونس)', 'ar-TN', 'Arabic (Tunisia)'],
    ['العربية (عُمان)', 'ar-OM', 'Arabic (Oman)'],
    ['العربية (فلسطين)', 'ar-PS', 'Arabic (State of Palestine)'],
    ['العربية (قطر)', 'ar-QA', 'Arabic (Qatar)'],
    ['العربية (لبنان)', 'ar-LB', 'Arabic (Lebanon)'],
    ['العربية (مصر)', 'ar-EG', 'Arabic (Egypt)'],
    ['فارسی (ایران)', 'fa-IR', 'Persian (Iran)'],
    ['हिन्दी (भारत)', 'hi-IN', 'Hindi (India)'],
    ['ไทย (ประเทศไทย)', 'th-TH', 'Thai (Thailand)'],
    ['한국어 (대한민국)', 'ko-KR', 'Korean (South Korea)'],
    ['國語 (台灣)', 'cmn-Hant-TW', 'Chinese, Mandarin (Traditional, Taiwan)'],
    ['廣東話 (香港)', 'yue-Hant-HK', 'Chinese, Cantonese (Traditional, Hong Kong)'],
    ['日本語（日本）', 'ja-JP', 'Japanese (Japan)'],
    ['普通話 (香港)', 'cmn-Hans-HK', 'Chinese, Mandarin (Simplified, Hong Kong)'],
    ['普通话 (中国大陆)', 'cmn-Hans-CN', 'Chinese, Mandarin (Simplified, China)']
];
